
from student import Question
history = Question("How old is Sibhi?", "19 years old")
social_media = Question("Which tech entrepreneur invented the social media site, Twitter?", "Jack Dorsey")
#print(history.prompt)
#print(history.answer)
#print(social_media.prompt)
#print(social_media.answer)

from student import Student
student1 = Student("Thilaga", "SAS : Zoology", 3.7, False)
student2 = Student("Sibhi", "SOE : Computer Engineering", 3.99, False) 
student3 = Student("Jarvis", "SAS : Art History", 3.49, False)
student4 = Student("Trevor", "BUS : Communications", 3.85, True)
student5 = Student("James", "SOE : Biomedical Engineering", 3.65, True)
student6 = Student("Trina", "SOE : Chemical Engineering", 3.87, False)
student7 = Student("Katalina", "BUS : Finance", 3.88, True)
student8 = Student("Jerome", "BUS : Marketing", 3.80, False)
student9 = Student("Frank", "SOE : Mechanical Engineering", 3.90, False)
student10 = Student("Blake", "SAS : Computer Science", 3.70, False)
student11 = Student("Dominic", "SAS : Biology", 3.97, False)

print(student1.name)
print(student1.gpa)
print(student1.is_on_probation)
print(student1.on_honor_roll())
print(student1.engineering())
print(student1.years_to_manage())
print(student1.scholar())

print(student2.name)
print(student2.gpa)
print(student2.is_on_probation)
print(student2.on_honor_roll())
print(student2.engineering())
print(student2.years_to_manage())
print(student2.scholar())


print(student3.name)
print(student3.gpa)
print(student3.is_on_probation)
print(student3.on_honor_roll())
print(student3.engineering())
print(student3.years_to_manage())
print(student3.scholar())

print(student4.name)
print(student4.gpa)
print(student4.is_on_probation)
print(student4.on_honor_roll())
print(student4.engineering())
print(student4.years_to_manage())
print(student4.scholar())

print(student5.name)
print(student5.gpa)
print(student5.is_on_probation)
print(student5.on_honor_roll())
print(student5.engineering())
print(student5.years_to_manage())
print(student5.scholar())

print(student6.name)
print(student6.gpa)
print(student6.is_on_probation)
print(student6.on_honor_roll())
print(student6.engineering())
print(student6.years_to_manage())
print(student6.scholar())


print(student7.name)
print(student7.gpa)
print(student7.is_on_probation)
print(student7.on_honor_roll())
print(student7.engineering())
print(student7.years_to_manage())
print(student7.scholar())


print(student8.name)
print(student8.gpa)
print(student8.is_on_probation)
print(student8.on_honor_roll())
print(student8.engineering())
print(student8.years_to_manage())
print(student8.scholar())


print(student9.name)
print(student9.gpa)
print(student9.is_on_probation)
print(student9.on_honor_roll())
print(student9.engineering())
print(student9.years_to_manage())
print(student9.scholar())


print(student10.name)
print(student10.gpa)
print(student10.is_on_probation)
print(student10.on_honor_roll())
print(student10.engineering())
print(student10.years_to_manage())
print(student10.scholar())


print(student11.name)
print(student11.gpa)
print(student11.is_on_probation)
print(student11.on_honor_roll())
print(student11.engineering())
print(student11.years_to_manage())
print(student11.scholar())
